### ISSUE TITLE
Wrong route names

### ISSUE THREAD

**Issue by cozvtieg9** [Onix-Systems/onix-flutter-project-generator#28]
**Describe the bug**
Route names in wrong. Route name variable contains "path" and not used in route declaration.

**To Reproduce**
1. Go to AppRouter
2. Check Route names constants
3. Check actual route name in route declaring

**Expected behavior**
Route constants shooul be used in route declaration. Route names should not equals route path.

**Comment by DemeoStep** [comment]
fixed in release-1.0.17
