### ISSUE TITLE
Dedicated functionality for .jks 

### ISSUE THREAD

**Issue by dzen1984** [Onix-Systems/onix-flutter-project-generator#67]
I think it would be sensible to add dedicated functionality (without creating a project) for actions related to the generation Android jks key and also for getting SHA1/SHA256 fingerprints of the existing key.

**Comment by cozvtieg9** [comment]
Planned in [version 1.1.1 (26)](https://github.com/Onix-Systems/onix-flutter-project-generator/pull/68)
