### ISSUE TITLE
Wrong AppRoute enum generation

### ISSUE THREAD

**Issue by DemeoStep** [Onix-Systems/onix-flutter-project-generator#78]
**Describe the bug**
Adding new screen provides adding new AppRoute enum name with error

**To Reproduce**
Add new screen into existing project with already present screen

**Expected behavior**
<img width="316" alt="Screenshot 2024-06-23 at 12 55 04" src="https://github.com/Onix-Systems/onix-flutter-project-generator/assets/66169659/6b67131a-1ebb-4645-870a-59543e6bea6d">

**Screenshots**
<img width="316" alt="Screenshot 2024-06-23 at 12 50 21" src="https://github.com/Onix-Systems/onix-flutter-project-generator/assets/66169659/600750c2-b404-48fa-bd79-2a75653e44b0">

**Comment by Coloud1** [comment]
The bug has not been reproduced. If the problem appeared in 1.1.3-1.1.4 version, then open this issue
